# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Cython wrapper for Rust FFI for curve_intersection module."""

from bezier._status cimport Status

# Define uint8_t if not already defined (e.g. in another .pxd file that might be included first)
# For safety, can be defined here.
ctypedef unsigned char uint8_t

cdef extern from "../../rust/target/include/bezier_rust_ffi.h":
    # BoxIntersectionType enum is likely defined in the Rust-generated header if used in FFI.
    # Assuming it's generated by cbindgen based on its usage in BEZ_bbox_intersect.
    # If not, it might need to be defined here or in a common types pxd.
    # For now, let's assume it's in bezier_rust_ffi.h.
    # cdef enum BoxIntersectionType: # This might be auto-generated
    #     INTERSECTION = 0
    #     TANGENT = 1
    #     DISJOINT = 2

    void BEZ_newton_refine_curve_intersect(
        double s, int num_nodes1,
        const double* nodes1, double t, int num_nodes2,
        const double* nodes2, double* new_s, double* new_t, Status* status_code) # status_code matches Rust
    void BEZ_bbox_intersect(
        int num_nodes1, const double* nodes1,
        int num_nodes2, const double* nodes2, int* enum_) # Assuming BoxIntersectionType maps to int
    # The Fortran ABI for all_intersections_abi does not have `coincident`.
    # It has: num_nodes1, nodes1, num_nodes2, nodes2, max_intersections, intersections_ptr, num_intersections_ptr, status_code
    void BEZ_all_intersections_abi( # Renamed to match the likely FFI name from Rust
        int num_nodes_first,
        const double* nodes_first, int num_nodes_second,
        const double* nodes_second, int max_intersections, # Renamed intersections_size
        double* intersections, int* num_intersections, # Made num_intersections an output pointer
        Status* status_code) # Added status_code
    void BEZ_free_curve_intersections_workspace()
