# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Cython wrapper for Rust FFI for triangle_intersection module."""

from bezier._status cimport Status

# Define uint8_t if not already defined
ctypedef unsigned char uint8_t

cdef extern from "../../rust/target/include/bezier_rust_ffi.h":
    # Assuming TriangleContained and CurvedPolygonSegment are generated by cbindgen
    # cdef enum TriangleContained:
    #     NEITHER = 0
    #     FIRST = 1
    #     SECOND = 2
    #
    # ctypedef struct CurvedPolygonSegment:
    #     double start
    #     double end_ # Changed from 'end' if it's a keyword problem in Rust/C, matching prior style
    #     int edge_index

    # Based on the translated Rust code for `triangle_intersection.rs`
    void BEZ_newton_refine_triangle(
        int num_nodes, const double* nodes, // dimension is implicitly 2
        int degree, double x_val, double y_val,
        double s, double t, double* updated_s, double* updated_t)
    
    # BEZ_locate_point_triangle was not in the provided FFI list for triangle_intersection.rs
    # If it exists in bezier_rust_ffi.h, its signature would be:
    # void BEZ_locate_point_triangle(
    #     int num_nodes, const double* nodes, // dimension is implicitly 2
    #     int degree, double x_val, double y_val, 
    #     double* s_val, double* t_val, Status* status_code) # Added status

    # BEZ_triangle_intersections corresponds to triangles_intersect_abi in Fortran.
    # The Fortran ABI: num_nodes1, nodes1, degree1, num_nodes2, nodes2, degree2,
    # max_elements, segment_ends, segments, num_elements_ptr, status_ptr
    # Assuming CurvedPolygonSegment is defined in bezier_rust_ffi.h
    ctypedef struct CurvedPolygonSegment: # Ensure this matches the C header
        double start_param "start" # Use field names from C, not necessarily from Rust struct
        double end_param "end_" 
        int edge_index

    void BEZ_triangle_intersections_abi(
        int num_nodes1, const double* nodes1, int degree1,
        int num_nodes2, const double* nodes2, int degree2,
        int max_intersections, # max_elements in Fortran
        CurvedPolygonSegment* segments, # segments in Fortran
        int* num_intersected,  # num_elements_ptr
        int* contained, # TriangleContained* (maps to int*)
        Status* status_code) # status_ptr

    void BEZ_free_triangle_intersections_workspace()
